---
version: '3.8'

services:
  api:
    image: summerthe/summers_api
    container_name: summersapi
    ports:
      - 80:8000
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    container_name: summers_redis
    restart: unless-stopped
    ports:
      - 6379:6379
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  celery_worker:
    image: summerthe/summers_api
    container_name: django_celery_worker
    command:
      [
        "celery",
        "-A",
        "summers_api",
        "worker",
        "-B",
        "-l",
        "INFO",
        "-Q",
        "tube2drive_queue",
        "-s",
        "/tmp/celerybeat-schedule",
        "--concurrency=1"
      ]
    env_file: .env
    depends_on:
      - redis
