---
version: '3.8'

services:
  api:
    image: summerthe/summers_api
    container_name: summersapi
    ports:
      - 80:8000
    env_file: .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - 6379:6379

  celery_worker:
    image: summerthe/summers_api
    container_name: django_celery_worker
    command:
      [
        "celery",
        "-A",
        "summers_api",
        "worker",
        "-B",
        "-l",
        "INFO",
        "-Q",
        "tube2drive_queue",
        "-s",
        "/tmp/celerybeat-schedule",
        "--concurrency=1"
      ]
    env_file: .env
    depends_on:
      - redis
