# Generated by Django 3.2.13 on 2022-07-23 05:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unique_identifier', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Unique Identifier')),
                ('youtube_link', models.URLField()),
                ('youtube_entity_name', models.CharField(blank=True, max_length=255, null=True)),
                ('folder_link', models.URLField()),
                ('status', models.CharField(blank=True, choices=[('START', 'START'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FOLDER_NOT_FOUND', 'FOLDER_NOT_FOUND'), ('PLAYLIST_NOT_FOUND', 'PLAYLIST_NOT_FOUND'), ('VIDEO_NOT_FOUND', 'VIDEO_NOT_FOUND'), ('CHANNEL_NOT_FOUND', 'CHANNEL_NOT_FOUND')], default='START', max_length=25)),
                ('slug', models.SlugField(editable=False, max_length=400, unique=True)),
            ],
            options={
                'verbose_name': 'UploadRequest',
                'verbose_name_plural': 'UploadRequests',
                'ordering': ['-updated_at'],
            },
        ),
    ]
