# Generated by Django 3.2.13 on 2022-07-03 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube2drive', '0002_uploadrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadrequest',
            name='status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('RUNNING', 'RUNNING'), ('COMPLETED', 'COMPLETED'), ('FOLDER_NOT_FOUND', 'FOLDER_NOT_FOUND'), ('PLAYLIST_NOT_FOUND', 'PLAYLIST_NOT_FOUND')], default='START', max_length=25),
        ),
    ]
